name: Deploy HTML Application

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Clean up existing run.sh
      run: |
        if [ -f "/home/duniacloud6_gmail_com/run.sh" ]; then
          rm /home/duniacloud6_gmail_com/run.sh
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to web server directory
      run: |
        sudo cp -R * /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/

    - name: Restart web server (if necessary)
      run: |
        service nginx restart

    - name: Clean up
      run: |
        sudo find /var/www/html/ -type f -not -path "*/.*" -delete

    - name: Final cleanup
      if: always()
      run: |
        if [ -f "/home/duniacloud6_gmail_com/run.sh" ]; then
          rm /home/duniacloud6_gmail_com/run.sh
        fi