name: Deploy HTML Application

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to web server directory
      run: |
        sudo cp -R * /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/

    - name: Restart web server (if necessary)
      run: |
        sudo systemctl restart apache2  # or nginx, depending on your web server

    - name: Clean up
      run: |
        sudo find /var/www/html/ -type f -not -path "*/.*" -delete